apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-labels-helper-configmap
  {{- template "mychart.labels" }}
data:
  myvalue: "Hello World"
  {{- range $key, $val := .Values.favorite }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}